### PR TITLE
Added permission request feature is declined by user

### PR DESCRIPTION
**Pull request by muarachmann**
Signed-off-by: Mua Rachmann <muarachmann@gmail.com>

### CODE REVIEW

**Comment by muarachmann** [comment]
oops i guess i need to rebase this

**Comment by muarachmann** [comment]
@ngengesenior added the functionality to ask user to grant sms permission again if they ever refused in future, let me know if you need some improvements since I just did it off the shell

**Comment by ngengesenior** [comment]
@muarachmann I thought I had that implemented in the Splash Activity?

**Comment by ngengesenior** [comment]
One more thing too, there was a quick change. I switched to using the new navigation component and factored MainActivity into NavigationActivity. I will have a look again because I thought I implemented Runtime permissions

**Comment by muarachmann** [comment]
@ngengesenior you did but this prompts in again when the user denied on first instance. The default way was that when the user did decline and comes back to the app, the app quits rather this pops up telling the user to grant access and also can be played with when switched from different screens.

Screen Shot 2020-03-06 at 9 28 20 AM

More over I updated the readme and added how one could test with the emulator and simulate messages from ECOBANK or the different providers. have a look https://github.com/muarachmann/ExpenseStats/blob/fix-permissions/README.md. This was my case as I don't have an Ecobank nor android device. So had to use the emulator... Nevertheless it works good so far
h

**Pull request merged**
